stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: go build -o server server.go
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: patricktest/server:v1
      pushRemote: true
      registry: 127.0.0.1:34187
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
